// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxC9RRzXzE5LWU90NiF0BPB6d2qhHU96E',
    appId: '1:193450119891:web:016ef1f20113a737f07a26',
    messagingSenderId: '193450119891',
    projectId: 'dicoding-chatting-5c752',
    authDomain: 'dicoding-chatting-5c752.firebaseapp.com',
    storageBucket: 'dicoding-chatting-5c752.appspot.com',
    measurementId: 'G-T5S5L80K8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiVOTURkBXFtlhlS_A2EyzhFwlCqReo14',
    appId: '1:193450119891:android:0f3c5a0489c88fa9f07a26',
    messagingSenderId: '193450119891',
    projectId: 'dicoding-chatting-5c752',
    storageBucket: 'dicoding-chatting-5c752.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9Lt5V3QBcMAyjrlEeCo939-hNalYRAr0',
    appId: '1:193450119891:ios:cdcb22444558725cf07a26',
    messagingSenderId: '193450119891',
    projectId: 'dicoding-chatting-5c752',
    storageBucket: 'dicoding-chatting-5c752.appspot.com',
    iosClientId: '193450119891-guietb3o1gnljh2auu9jkjmdlntcrjpg.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.dicodingChatting',
  );
}
